In [1]:
#!pip install pandas
import pandas as pd
ler_arquivo = pd.read_csv('downloads/alcool_2021.csv', error_bad_lines=False, delimiter=';')
df_exemplo = ler_arquivo
# Changing columns name with index number
tab_2021_excessopeso = df_exemplo.rename(columns={df_exemplo.columns[7]: 'Masculino_2021',df_exemplo.columns[10]: 'Feminino_2021', df_exemplo.columns[4]: 'Total_2021'})
tab_2021_excessopeso = tab_2021_excessopeso[['Indicador', 'Variável','Faixa', 'Total_2021', 'Masculino_2021', 'Feminino_2021']]
ler_arquivo = pd.read_csv('downloads/alcool_2011.csv', error_bad_lines=False, delimiter=';')
df_arquivo2 = ler_arquivo
# Changing columns name with index number
tab_2011_excessopeso = df_arquivo2.rename(columns={df_arquivo2.columns[7]: 'Masculino_2011',df_arquivo2.columns[10]: 'Feminino_2011', df_arquivo2.columns[4]: 'Total_2011'})
tab_2011_excessopeso.loc[tab_2011_excessopeso.Variável == 'Idade (anos)']
excesso_peso_2011 = tab_2011_excessopeso.loc[tab_2011_excessopeso.Variável == 'Idade (anos)']
excesso_peso_2021 = tab_2021_excessopeso.loc[tab_2021_excessopeso.Variável == 'Idade (anos)']
df_novo_x = pd.merge(excesso_peso_2011, excesso_peso_2021, on="Faixa")
df_final = df_novo_x[['Indicador_x','Faixa', 'Total_2011', 'Total_2021','Masculino_2011', 'Masculino_2021', 'Feminino_2011', 'Feminino_2021']]
df_final['Total_2011'] = pd.to_numeric(df_final['Total_2011'].str.replace(',', '.').astype(float), downcast='float')
df_final['Total_2021'] = pd.to_numeric(df_final['Total_2021'].str.replace(',', '.').astype(float), downcast='float')
df_final['Masculino_2021'] = pd.to_numeric(df_final['Masculino_2021'].str.replace(',', '.').astype(float), downcast='float')
df_final['Masculino_2011'] = pd.to_numeric(df_final['Masculino_2011'].str.replace(',', '.').astype(float), downcast='float')
df_final['Feminino_2021'] = pd.to_numeric(df_final['Feminino_2021'].str.replace(',', '.').astype(float), downcast='float')
df_final['Feminino_2011'] = pd.to_numeric(df_final['Feminino_2011'].str.replace(',', '.').astype(float), downcast='float')
df_final['Variacao_fem'] = df_final['Feminino_2021'] - df_final['Feminino_2011']
df_final['Variacao_masc'] = df_final['Masculino_2021'] - df_final['Masculino_2011']
df_final['Variacao_total'] = df_final['Total_2021'] - df_final['Total_2011']
df_final.round(2)

/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  ler_arquivo = pd.read_csv('downloads/alcool_2021.csv', error_bad_lines=False, delimiter=';')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:8: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  ler_arquivo = pd.read_csv('downloads/alcool_2011.csv', error_bad_lines=False, delimiter=';')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Total_2011'] = pd.to_numeric(df_final['Total_2011'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Total_2021'] = pd.to_numeric(df_final['Total_2021'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Masculino_2021'] = pd.to_numeric(df_final['Masculino_2021'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Masculino_2011'] = pd.to_numeric(df_final['Masculino_2011'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Feminino_2021'] = pd.to_numeric(df_final['Feminino_2021'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Feminino_2011'] = pd.to_numeric(df_final['Feminino_2011'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Variacao_fem'] = df_final['Feminino_2021'] - df_final['Feminino_2011']
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Variacao_masc'] = df_final['Masculino_2021'] - df_final['Masculino_2011']
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3572/4242404898.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Variacao_total'] = df_final['Total_2021'] - df_final['Total_2011']

,Indicador_x,Faixa,Total_2011,Total_2021,Masculino_2011,Masculino_2021,Feminino_2011,Feminino_2021,Variacao_fem,Variacao_masc,Variacao_total
0,"Percentual de adultos (≥ 18 anos) que, nos últ...",18 a 24,20.209999,19.280001,27.930000,22.139999,12.23,16.059999,3.83,-5.79,-0.93
1,"Percentual de adultos (≥ 18 anos) que, nos últ...",25 a 34,21.309999,25.490000,32.450001,30.910000,10.99,20.760000,9.77,-1.54,4.18
2,"Percentual de adultos (≥ 18 anos) que, nos últ...",35 a 44,18.219999,20.049999,27.309999,29.209999,10.70,12.790000,2.09,1.90,1.83
3,"Percentual de adultos (≥ 18 anos) que, nos últ...",45 a 54,14.830000,17.950001,22.049999,26.700001,8.90,10.140000,1.24,4.65,3.12
4,"Percentual de adultos (≥ 18 anos) que, nos últ...",55 a 64,10.560000,13.200000,18.430000,20.580000,4.60,7.550000,2.95,2.15,2.64
5,"Percentual de adultos (≥ 18 anos) que, nos últ...",65 e mais,4.470000,5.790000,8.150000,9.450000,2.05,3.250000,1.20,1.30,1.32

In [2]:
df_final

,Indicador_x,Faixa,Total_2011,Total_2021,Masculino_2011,Masculino_2021,Feminino_2011,Feminino_2021,Variacao_fem,Variacao_masc,Variacao_total
0,"Percentual de adultos (≥ 18 anos) que, nos últ...",18 a 24,20.209999,19.280001,27.930000,22.139999,12.23,16.059999,3.830000,-5.790001,-0.929998
1,"Percentual de adultos (≥ 18 anos) que, nos últ...",25 a 34,21.309999,25.490000,32.450001,30.910000,10.99,20.760000,9.770000,-1.540001,4.180000
2,"Percentual de adultos (≥ 18 anos) que, nos últ...",35 a 44,18.219999,20.049999,27.309999,29.209999,10.70,12.790000,2.090000,1.900000,1.830000
3,"Percentual de adultos (≥ 18 anos) que, nos últ...",45 a 54,14.830000,17.950001,22.049999,26.700001,8.90,10.140000,1.240001,4.650002,3.120001
4,"Percentual de adultos (≥ 18 anos) que, nos últ...",55 a 64,10.560000,13.200000,18.430000,20.580000,4.60,7.550000,2.950000,2.150000,2.639999
5,"Percentual de adultos (≥ 18 anos) que, nos últ...",65 e mais,4.470000,5.790000,8.150000,9.450000,2.05,3.250000,1.200000,1.300000,1.320000

In [3]:
# converting to CSV file
df_final.to_csv("alcool.csv")