In [1]:
ç

/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  ler_arquivo = pd.read_csv('downloads/hipert_2021.csv', error_bad_lines=False, delimiter=';')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:8: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  ler_arquivo = pd.read_csv('downloads/hipert_2011.csv', error_bad_lines=False, delimiter=';')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Total_2011'] = pd.to_numeric(df_final['Total_2011'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Total_2021'] = pd.to_numeric(df_final['Total_2021'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Masculino_2021'] = pd.to_numeric(df_final['Masculino_2021'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Masculino_2011'] = pd.to_numeric(df_final['Masculino_2011'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Feminino_2021'] = pd.to_numeric(df_final['Feminino_2021'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Feminino_2011'] = pd.to_numeric(df_final['Feminino_2011'].str.replace(',', '.').astype(float), downcast='float')
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Variacao_fem'] = df_final['Feminino_2021'] - df_final['Feminino_2011']
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Variacao_masc'] = df_final['Masculino_2021'] - df_final['Masculino_2011']
/var/folders/kq/pf42y0p14nz9g39mh_c2zh0w0000gn/T/ipykernel_3537/931264738.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Variacao_total'] = df_final['Total_2021'] - df_final['Total_2011']

,Indicador_x,Faixa,Total_2011,Total_2021,Masculino_2011,Masculino_2021,Feminino_2011,Feminino_2021,Variacao_fem,Variacao_masc,Variacao_total
0,Percentual de adultos (≥ 18 anos) que referira...,18 a 24,3.980000,3.760000,4.100000,3.090000,3.850000,4.520000,0.67,-1.01,-0.22
1,Percentual de adultos (≥ 18 anos) que referira...,25 a 34,9.360000,12.240000,9.200000,13.930000,9.510000,10.770000,1.26,4.73,2.88
2,Percentual de adultos (≥ 18 anos) que referira...,35 a 44,19.629999,18.590000,18.879999,19.850000,20.250000,17.600000,-2.65,0.97,-1.04
3,Percentual de adultos (≥ 18 anos) que referira...,45 a 54,34.419998,30.920000,31.490000,32.779999,36.830002,29.260000,-7.57,1.29,-3.50
4,Percentual de adultos (≥ 18 anos) que referira...,55 a 64,49.959999,49.400002,45.360001,46.360001,53.450001,51.720001,-1.73,1.00,-0.56
5,Percentual de adultos (≥ 18 anos) que referira...,65 e mais,59.669998,61.000000,52.619999,57.049999,64.309998,63.740002,-0.57,4.43,1.33

In [2]:
df_final

,Indicador_x,Faixa,Total_2011,Total_2021,Masculino_2011,Masculino_2021,Feminino_2011,Feminino_2021,Variacao_fem,Variacao_masc,Variacao_total
0,Percentual de adultos (≥ 18 anos) que referira...,18 a 24,3.980000,3.760000,4.100000,3.090000,3.850000,4.520000,0.670000,-1.010000,-0.220000
1,Percentual de adultos (≥ 18 anos) que referira...,25 a 34,9.360000,12.240000,9.200000,13.930000,9.510000,10.770000,1.260000,4.730000,2.880000
2,Percentual de adultos (≥ 18 anos) que referira...,35 a 44,19.629999,18.590000,18.879999,19.850000,20.250000,17.600000,-2.650000,0.970001,-1.039999
3,Percentual de adultos (≥ 18 anos) que referira...,45 a 54,34.419998,30.920000,31.490000,32.779999,36.830002,29.260000,-7.570002,1.289999,-3.499998
4,Percentual de adultos (≥ 18 anos) que referira...,55 a 64,49.959999,49.400002,45.360001,46.360001,53.450001,51.720001,-1.730000,1.000000,-0.559998
5,Percentual de adultos (≥ 18 anos) que referira...,65 e mais,59.669998,61.000000,52.619999,57.049999,64.309998,63.740002,-0.569996,4.430000,1.330002

In [3]:
# converting to CSV file
df_final.to_csv("hipert.csv")